steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nifty-screener-repo/nifty-screener:latest'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nifty-screener-repo/nifty-screener:latest'

options:
  logging: CLOUD_LOGGING_ONLY