steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.xauusd'
      - '-t'
      - 'asia-south1-docker.pkg.dev/project-438fa76a-0dff-43fd-b67/nifty-screener-repo/xauusd-forex-bot:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/project-438fa76a-0dff-43fd-b67/nifty-screener-repo/xauusd-forex-bot:latest'

images:
  - 'asia-south1-docker.pkg.dev/project-438fa76a-0dff-43fd-b67/nifty-screener-repo/xauusd-forex-bot:latest'

options:
  logging: CLOUD_LOGGING_ONLY