name: FII DII Daily Alert

on:
  schedule:
    # Monday to Friday 6:30 PM IST (13:00 UTC)
    - cron: '0 13 * * 1-5'
  workflow_dispatch: # Manual test-kaga

jobs:
  fii-dii-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch and Send FII DII
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python fii_dii.py
